name: update

permissions:
  contents: write

on:
  push:
    branches: [ main ]
    paths:
      - 'data/*.json'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  full_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: create the visualization
        run: python update.py
      - name: commit and push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
